# $Id: FindRT.cmake
#
SET(RT_NAMES rt)
FIND_LIBRARY(RT_LIBRARY NAMES ${RT_NAMES} )
# handle the QUIETLY and REQUIRED arguments and set RT_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RT DEFAULT_MSG RT_LIBRARY)
IF(RT_FOUND)
    SET( RT_LIBRARIES ${RT_LIBRARY} )
ELSE(RT_FOUND)
    SET( RT_LIBRARIES )
ENDIF(RT_FOUND)
MARK_AS_ADVANCED( RT_LIBRARIES )
