#
# $Id: FindDL.cmake
#
SET(DL_NAMES dl)
FIND_LIBRARY(DL_LIBRARY NAMES ${DL_NAMES} )
# handle the QUIETLY and REQUIRED arguments and set DL_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(DL DEFAULT_MSG DL_LIBRARY)
IF(DL_FOUND)
    SET( DL_LIBRARIES ${DL_LIBRARY} )
ELSE(DL_FOUND)
    SET( DL_LIBRARIES )
ENDIF(DL_FOUND)
MARK_AS_ADVANCED( DL_LIBRARIES )
