FIND_PATH(LibCURL_INCLUDE_DIR curl.h)

SET(LibCURL_NAMES ${LibCURL_NAMES} curl)
FIND_LIBRARY(LibCURL_LIBRARY NAMES ${LibCURL_NAMES}) 

INCLUDE(MacroFindPackageWithCache)

MACRO_FIND_PACKAGE_WITH_CACHE(
  libcurl LibCURL curl/curl.h curl
)

IF(LibCURL_FOUND)
  SET(LibCURL_LIBRARIES ${LibCURL_LIBRARY})
  MESSAGE(STATUS "Find LibCURL : ${LibCURL_LIBRARIES}" )
ENDIF(LibCURL_FOUND)

MARK_AS_ADVANCED(LibCURL_LIBRARIES LibCURL_INCLUDE_DIR )

