# MACRO_SET_DEFAULT_BUILD_TYPE(name)
#

MACRO(MACRO_SET_DEFAULT_BUILD_TYPE name)

  IF(NOT CMAKE_BUILD_TYPE)
    SET(CMAKE_BUILD_TYPE "${name}")
  ENDIF(NOT CMAKE_BUILD_TYPE)
  SET(CMAKE_BUILD_TYPE "${CMAKE_BUILD_TYPE}" CACHE STRING
    "Choose the build type: ${CMAKE_CONFIGURATION_TYPES}")

ENDMACRO(MACRO_SET_DEFAULT_BUILD_TYPE)
